[package]
name = "rust-unity"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
time = { version = "0.3.36", features = ["serde", "serde-human-readable"] }
rand = "0.9.0-alpha.2"