// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace RustLib
{
    public static unsafe partial class Lib
    {
        const string __DllName = "rust_unity";



        [DllImport(__DllName, EntryPoint = "add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int add(int a, int b);

        [DllImport(__DllName, EntryPoint = "get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Obj* get();

        [DllImport(__DllName, EntryPoint = "alloc_u8_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer* alloc_u8_string();

        [DllImport(__DllName, EntryPoint = "alloc_u8_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer* alloc_u8_buffer();

        [DllImport(__DllName, EntryPoint = "alloc_i32_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer* alloc_i32_buffer();

        [DllImport(__DllName, EntryPoint = "free_byte_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_byte_buffer(ByteBuffer* buffer);

        [DllImport(__DllName, EntryPoint = "create_game", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern MinesweeperGame* create_game(int width, int height, int mine_count);

        [DllImport(__DllName, EntryPoint = "free_game", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_game(MinesweeperGame* game);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void set_on_game_over_callback_delegate(bool arg1, int arg2, int arg3);

        [DllImport(__DllName, EntryPoint = "set_on_game_over", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void set_on_game_over(MinesweeperGame* game, set_on_game_over_callback_delegate callback);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void set_on_open_block_callback_delegate(int arg1, int arg2);

        [DllImport(__DllName, EntryPoint = "set_on_open_block", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void set_on_open_block(MinesweeperGame* game, set_on_open_block_callback_delegate callback);

        [DllImport(__DllName, EntryPoint = "open_block", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool open_block(MinesweeperGame* game, int x, int y);

        [DllImport(__DllName, EntryPoint = "flag_block", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool flag_block(MinesweeperGame* game, int x, int y);

        [DllImport(__DllName, EntryPoint = "get_block", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern Block* get_block(MinesweeperGame* game, int x, int y);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Obj
    {
        public ByteBuffer* name;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct Block
    {
        public int x;
        public int y;
        public int num;
        [MarshalAs(UnmanagedType.U1)] public bool is_mine;
        [MarshalAs(UnmanagedType.U1)] public bool is_flag;
        [MarshalAs(UnmanagedType.U1)] public bool is_opened;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct MinesweeperGame
    {
    }



}
